name: flutter_google_datastore
description: A flutter project to browse a google datastore
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  ulid4d: ^2.0.0
  sqflite_common_ffi_web: ^0.4.0
  settings_ui: ^2.0.2
  googleapis: ^11.4.0
  path_provider: ^2.1.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.11
  googleapis_auth: ^1.4.1
  toml: ^0.14.0
  ini: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
