name: flutter_google_datastore
description: A flutter project to browse a google datastore
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  sqflite_common_ffi_web: ^1.0.0
  ulid4d: ^2.0.0
  settings_ui: ^2.0.2
  googleapis: ^14.0.0
  path_provider: ^2.1.5
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  googleapis_auth: ^2.0.0
  toml: ^0.16.0
  ini: ^2.1.0
  infinite_scroll_pagination: ^4.0.0
  timezone: ^0.10.0
  file_picker: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter:
  assets:
    - assets/logo.png
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
