display_name: Flutter Google Datastore
package_name: flutter-google-datastore
maintainer:
  name: Arran Ubels
  email: arran@ubels.com.au
priority: optional
section: x11
installed_size: 6604
essential: false
icon: assets/logo.png

generic_name: Misc Applications

categories:
  - Utility

startup_notify: true
