# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
app_id: a4f7f615-7e43-4f0a-9846-bc8f46512067
publisher: Arran4
publisher_url: https://github.com/arran4/flutter_google_datastore
display_name: Flutter Google Datastore
create_desktop_icon: true
install_dir_name: FLUTTER-Google-Datastore
locales:
  - en
