name: Test

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

env:
  FLUTTER_SDK_VERSION: '3.32.2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.7.0'
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FLUTTER_SDK_VERSION }}
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test --no-pub
